services:
  jira-tickets-from-gh:
    volumes:
      - data:/home/app/data
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    image: jira-tickets-from-gh
    # network mode should not be host, for some reason my docker containers
    # dont have internat access :(
    network_mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      GITHUB_TOKEN: /run/secrets/github_token
      JIRA_EMAIL: ${JIRA_EMAIL}
      JIRA_TOKEN: /run/secrets/jira_token
      # Modify this and/or add more jira_token_{{project_name}}
      # secrets for multiple jira subdomains support
      # JIRA_TOKEN_{{project_name}}: /run/secrets/jira_token_{{project_name}}
      # JIRA_EMAIL_{{project_name}}: ${JIRA_EMAIL_{{project_name}}}
      VERBOSE: ${VERBOSE}
    secrets:
      - jira_token
      - github_token
secrets:
  jira_token:
    environment: "JIRA_TOKEN"
  # Modify this and/or add more jira_token_{{project_name}}
  # secrets for multiple jira subdomains support
  # jira_token_{{project_name}}:
  #   environment: "JIRA_TOKEN_{{project_name}}"
  github_token:
    environment: "GITHUB_TOKEN"
volumes:
  data:
